### PR TITLE
Add general pre-boot and kernel installation documentation

### PR DESCRIPTION
**Pull request by OddBloke**

### CODE REVIEW

**Review by rcj4747 — COMMENTED** [review]
The changes look good (barring 'make spelling' complaints).  I did not check the kernel modification changes manually though I do wonder about where we push /etc/resolv.conf into the chroot in our recipes; with that missing here will it resolve hosts for 'apt-get' operations?  Have you checked this?

**Review by rcj4747 — APPROVED** [review]
Since you've manually tested I'll approve.

**Comment by OddBloke** [comment]
We use the `--system-resolvconf` flag to mount-image-callback, which handles that for us.

**Review by josvazg — COMMENTED** [review]
What am I doing wrong?

Followed the instructions in yakkety and I got:

$ sudo mount-image-callback xenial.img -- mchroot cat /etc/cloud/build.info
[sudo] password for josvaz: 
/usr/bin/mount-image-callback: line 429: mchroot: command not found

**Comment by OddBloke** [comment]
@josvazg I've updated the instructions to work on all releases (at least back to trusty).

Turns out mchroot was introduced between yakkety and zesty, so we shouldn't use that.

**Review by josvazg — APPROVED** [review]
LGTM!

Tested all commands run properly now on my yakkety.

**Pull request merged**
