### PR TITLE
Configure basic Sphinx/travis stuff

### PR DESCRIPTION
**Pull request by OddBloke**
My plan is to have Sphinx documentation that makes understanding what the repository contains a little easier, but still have all the configuration snippets in separate files (which Sphinx pulls in) so they are also easy to consume in automation/copy-paste.

### CODE REVIEW

**Review by josvazg — COMMENTED** [review]
Not very familiar with Sphinx, so I just have some doubts:
To make this work (generate an HTML site) I had to:

$ mkvirtualenv somename
(somename) $ pip install sphinx
(somename) $ make html

Shouldn't we have that in the Readme?
Or are we going to auto generate the site somehow on a later commit?

UPDATE: I later saw the details in travis.yaml, but I still am not sure if this is supposed to have a script you run later on of the user needs to know the steps from the readme.

**Comment by OddBloke** [comment]
On 14/03/17 13:19, josvazg wrote:
> Not very familiar with Sphinx, so I just have some doubts:
> To make this work (generate an HTML site) I had to:
> 
> $ mkvirtualenv somename
> (somename) $ pip install sphinx
> (somename) $ make html

`pip install -r requirements.txt` would be better, but this is broadly
correct.

> Shouldn't we have that in the Readme?
> Or are we going to auto generate the site somehow on a later commit?

This is how Sphinx works in its default configuration[0], so I would
expect people to either know that, or be able to work that out (as you
did) without a README guide.  If we diverge from standard Sphinx
behaviour, then I'd be happy to consider it.  (I'm a little more
resistant than I might otherwise be, because the target audience for
this repo is not the developers of the repo, but our partners.)

I expect we will start auto-generating the site, but that is really
orthogonal; people will still want to test their changes locally.


[0] http://www.sphinx-doc.org/en/stable/tutorial.html#running-the-build

**Review by josvazg — APPROVED** [review]
After the explanation, LGTM!

**Review by rcj4747 — APPROVED** [review]
It all looks good. (I mean rendering index.rst as a manpage is odd looking but that's fine)

**Pull request merged**
